#!/usr/bin/env php
<?php

// Define base path
define('APP_BASE_PATH', __DIR__);

// Include autoloader
require_once "vendor/autoload.php";

// Create console kernel
$kernel = new Ody\Foundation\Console\ConsoleKernel();

// Bootstrap kernel
$kernel->bootstrap();

// Handle the request
$status = $kernel->handle();

exit($status);